[project]
name = "gaia-dr3-dimensionality-reduction"
version = "0.1.0"
description = "Dimensionality reduction experiments on Gaia DR3 dataset"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
